### PR TITLE
Add toolbar button that resets axes limits to 'Auto', and also added a colormap

### PR DESCRIPTION
**Pull request by arichar6**
Clicking the button loops through the selected widgets (and recursively through their children) and resets the limits on any Axis widgets to 'Auto'. This is a convenient way to "zoom back out" after zooming in on a plot.

Also added the "cool-warm" colormap from http://www.kennethmoreland.com/color-maps/ 
This colormap is a "diverging" colormap, and has many good qualities for scientific plots: http://dx.doi.org/10.1007/978-3-642-10520-3_9

### CODE REVIEW

**Comment by jeremysanders** [comment]
Thanks for the pull request. Sorry for the delay.

One problem is that I'm at unsure what the behaviour should be if there are multiple graphs in the plot. It's obvious for the axis zoom in, but not for a total document. This UI is a bit unclear.

Another problem is that if an axis is currently selected, this button only hast the effect of resetting that axis, not the whole graph.

The modifications to the axes are also done directly here. This isn't in line with how other document modifications are done. It should setup a document Operation which does the work. This would allow the axis reset to be undone.

I wonder whether a better approach would be to have a reset button appear next to an axis if it is selected (like the current axis position and range adjusters). The user could click on that axis, then the button to reset it.

Opinions?

PS The colormap looks good.

**Comment by arichar6** [comment]
I like the approach of having a "reset" button appear next to a selected axis. I think that UI is much more obvious than the toolbar button as I've currently implemented it. I was really just trying to hack together a "reset", since it is a feature that I've wanted for some time. I'm not sure how to implement such a button, but I'll take a look at the position and range adjusters for ideas as I get time.

Also, I wasn't aware of the document Operations... it's perfect for this and I'll use that from now on!

**Comment by arichar6** [comment]
Also, I'm not sure how the details of pull requests work. Should I close this and open another with just to colormap, so you can merge that? I had actually intended that to be a separate request, but it got lumped together with the reset stuff...

**Comment by mythsmith** [comment]
I added an alternative method and icon in my pull request 144. I can very easily changed it to update only the graph containing the currently selected widget, or all graphs in the current page if there is no selected widget.

**Pull request closed without merging**
