### PR TITLE
Added dataset label attribute and use it for auto plot key

### PR DESCRIPTION
**Pull request by mythsmith**
Addresses #139, #137, #145
* Dataset label is used as PointPlotter key if none is set and the dataset is yData. 
* The key is automatically updated on yData change. If the key is deleted, it a new attempt to read the dataset label is made.
* the dataset edit dialog now has a tabbed view: one tab for the data, one for the attributes.
data_tab
attr_tab
I made an very extensible attr table  because I plan to implement more feature building on #137 concept (units, hierarchy, etc).
- Added the magic .travis.yml which will cause TravisCI to automatically run tests upon each commit. 
See ours here: https://travis-ci.org/tainstr/veusz
- Added an alternative zoom-out icon and plugin in plugins/zoomaxes.py (alternative to #145 )
- Added an undo icon
new_icons
- Added a new utility class OperationWrapper, which ease grouping multiple operations in toolsplugin.

### CODE REVIEW

**Comment by KDB2** [comment]
You should review your PR. There is too much things inside. There is a problem.

**Comment by mythsmith** [comment]
Actually auto pep8 did a great job: the number of conflicts was incredibly low. 
Note that most of this stuff is really into pull request https://github.com/jeremysanders/veusz/pull/144, which is required for this to work. Unfortunately I only started now making separate branches for pull requests.

**Comment by KDB2** [comment]
I'm not an expert, but you can't commit 67 things at the same time and change 18 files. If there is a problem somewhere, it will be a nightmare to find it. 
You should only commit the last 3 commits, and if possible broken in 3 PR if they are not for the same idea.
One idea, one commit.

This said, it's up to Jeremy to decide what he is accepting or not.

**Comment by mythsmith** [comment]
I generally more than agree with you. 

1. In some cases, anyway, you need to touch tens of files just for a slight change. For example, to add the concept of a user/plugin-defined dataset attribute I had to change lots of datasets, command interfaces, and file saving mechanism, UI, etc. Without any of these edit all of the other changes lost their meaning or worse, results in bugs. 
2. Moreover, this particular case is really a merge of two divergent projects, including work spanning over the past 2 years. I need a common starting point to even think about making small PR in the future.
3. Auto-pep8 made lots of fixes which are just blank lines, newlines, or spaces around variables and function calls.

**Comment by mythsmith** [comment]
@jeremysanders 
If you think this is vital, I found a way to split this into 4 PR:
* travisci
* zoomaxes
* low-level dataset attrs
* attrs UI
Please advise.

**Comment by jeremysanders** [comment]
It would certainly be better split up, as I'd have a better chance understanding the code and reviewing it.

**Comment by mythsmith** [comment]
Let's close this pull request. Broke into:
#162 continuous integration
#163 zoom out of axes
#164 dataset attrs (really made no sense to split low and high level)

**Pull request closed without merging**
